### ISSUE TITLE
Move landrush-ip under the vagrant-landrush umbrella 

### ISSUE THREAD

**Issue by hferentschik** [vagrant-landrush/landrush-ip#4]
See also https://github.com/vagrant-landrush/landrush/issues/217

**Comment by Werelds** [comment]
Probably best to sort this before anything else. I can only transfer ownership to organisations I'm an admin in, so how do you want to go about this? Probably best if we hook up via Slack, Skype or even email to sort this out. Won't affect users directly, since the Gem is built and served separately.

**Comment by hferentschik** [comment]
Sounds good. I am currently on vacation though, hence the long delay. Back mid September. Let's have a chat then...

**Comment by Werelds** [comment]
This is now sorted :-)

**Comment by hferentschik** [comment]
Awesome thanks :-)
